version: "3"

services:
  arex:
    image: arexadmin01/arex:$AREX_VERSION
    container_name: arex-front
    restart: always
    ports:
      - '8088:8080'
    volumes:
      - ./arex-logs/arex-front:/usr/src/app/logs
    environment:
      - SERVICE_REPORT_URL=http://arex-api-service:8080
      - SERVICE_SCHEDULE_URL=http://arex-schedule-service:8080
      - SERVICE_STORAGE_URL=http://arex-storage-service:8080
    depends_on:
      - arex-api-service
      - arex-schedule-service
      - arex-storage-service

  arex-api-service:
    image: arexadmin01/arex-api:$AREX_VERSION
    container_name: arex-api
    restart: always
    ports:
      - '8090:8080'
    volumes:
      - ./arex-logs/arex-api:/logs
      - ./additional-config:/usr/local/tomcat/additional-config
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Darex.mongo.uri=$AREX_MONGO_URI
        -Darex.redis.uri=$AREX_REDIS_URI
        -Darex.storage.service.url=http://arex-storage-service:8080
        -Dspring.config.additional-location=/usr/local/tomcat/additional-config/
        -Dspring.config.name=application,oauth
    depends_on:
      - mongodb
      - redis
  arex-storage-service1:
    image: arexadmin01/arex-storage-serive:$AREX_VERSION
    container_name: arex-storage1
    restart: always
    ports:
      - '10093:8080'
    volumes:
      - ./arex-logs/arex-storage1:/logs
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Darex.mongo.uri=$AREX_MONGO_URI
        -Darex.redis.uri=$AREX_REDIS_URI
        -Darex.api.service.api=http://arex-api-service:8080
    depends_on:
      - mongodb
      - redis
  arex-storage-service2:
    image: arexadmin01/arex-storage-serive:$AREX_VERSION
    container_name: arex-storage2
    restart: always
    ports:
      - '11093:8080'
    volumes:
      - ./arex-logs/arex-storage2:/logs
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Darex.mongo.uri=$AREX_MONGO_URI
        -Darex.redis.uri=$AREX_REDIS_URI
        -Darex.api.service.api=http://arex-api-service:8080
    depends_on:
      - mongodb
      - redis
  arex-storage-service:
    container_name: storage-nginx
    image: nginx
    volumes:
      - ./conf/nginx-storage.conf:/etc/nginx/nginx.conf
      - ./arex-logs/nginx-storage:/var/log/nginx
    ports:
      - "8093:8080"
    depends_on:
      - arex-storage-service1
      - arex-storage-service2
  arex-schedule-service1:
    image: arexadmin01/arex-replay-schedule:$AREX_VERSION
    container_name: arex-schedule1
    restart: always
    ports:
      - '10092:8080'
    volumes:
      - ./arex-logs/arex-schedule1:/logs
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Darex.mongo.uri=$AREX_MONGO_URI
        -Darex.redis.uri=$AREX_REDIS_URI
        -Darex.storage.service.api=http://arex-storage-service:8080
        -Darex.api.service.api=http://arex-api-service:8080
    depends_on:
      - mongodb
      - redis
  arex-schedule-service2:
    image: arexadmin01/arex-replay-schedule:$AREX_VERSION
    container_name: arex-schedule2
    restart: always
    ports:
      - '11092:8080'
    volumes:
      - ./arex-logs/arex-schedule2:/logs
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Darex.mongo.uri=$AREX_MONGO_URI
        -Darex.redis.uri=$AREX_REDIS_URI
        -Darex.storage.service.api=http://arex-storage-service:8080
        -Darex.api.service.api=http://arex-api-service:8080
    depends_on:
      - mongodb
      - redis
  arex-schedule-service:
    container_name: schedule-nginx
    image: nginx
    volumes:
      - ./conf/nginx-schedule.conf:/etc/nginx/nginx.conf
      - ./arex-logs/nginx-schedule:/var/log/nginx
    ports:
      - "8092:8080"
    depends_on:
      - arex-schedule-service1
      - arex-schedule-service2
  mongodb:
    image: mongo:5.0
    container_name: arex-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./arex-data/mongodb:/data/db
      - ./mongo-allone-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./arex-logs/mongodb:/var/log/mongodb
    command: --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
      - MONGO_INITDB_DATABASE=rootdb
      - MONGO_USERNAME=arex
      - MONGO_PASSWORD=iLoveArex
  redis:
    image: redis:6.2.6
    container_name: arex-redis
    restart: always
    command: --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./arex-data/redis:/data
      - ./arex-logs/redis:/var/log/redis