version: "3"

services:
  arex:
    image: ${AREX_REGISTRY}arexadmin01/arex:${AREX_VERSION}
    container_name: arex-front
    restart: always
    ports:
      - '8088:8080'
    volumes:
      - ./arex-logs/arex-front:/usr/src/app/logs
    environment:
      - SERVICE_API_URL=http://arex-api-service:8080
      - SERVICE_SCHEDULE_URL=http://arex-schedule-service:8080
      - SERVICE_STORAGE_URL=http://arex-storage-service:8080
    depends_on:
      - arex-api-service
      - arex-schedule-service
      - arex-storage-service

  arex-api-service:
    image: ${AREX_REGISTRY}arexadmin01/arex-api:${AREX_VERSION}
    container_name: arex-api
    restart: always
    ports:
      - '8090:8080'
    volumes:
      - ./arex-logs/arex-api:/logs
      - ./additional-config:/usr/local/tomcat/additional-config
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Darex.mongo.uri=$AREX_MONGO_URI
        -Darex.redis.uri=$AREX_REDIS_URI
        -Darex.storage.service.url=http://arex-storage-service:8080 
        -Dspring.config.additional-location=/usr/local/tomcat/additional-config/
        -Dspring.config.name=application,oauth
    depends_on:
      - mongodb  
      - redis
  arex-storage-service:
    image: ${AREX_REGISTRY}arexadmin01/arex-storage-serive:${AREX_VERSION}
    container_name: arex-storage
    restart: always
    ports:
      - '8093:8080'
    volumes:
      - ./arex-logs/arex-storage:/logs
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Darex.mongo.uri=$AREX_MONGO_URI
        -Darex.redis.uri=$AREX_REDIS_URI 
        -Darex.api.service.api=http://arex-api-service:8080
    depends_on:
      - mongodb
      - redis
  arex-schedule-service:
    image: ${AREX_REGISTRY}arexadmin01/arex-replay-schedule:${AREX_VERSION}
    container_name: arex-schedule
    restart: always
    ports:
      - '8092:8080'
    volumes:
      - ./arex-logs/arex-schedule:/logs
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Darex.mongo.uri=$AREX_MONGO_URI
        -Darex.redis.uri=$AREX_REDIS_URI
        -Darex.storage.service.api=http://arex-storage-service:8080 
        -Darex.api.service.api=http://arex-api-service:8080
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:5.0
    container_name: arex-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./arex-data/mongodb:/data/db
      - ./mongo-allone-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./arex-logs/mongodb:/var/log/mongodb
    command: --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
      - MONGO_INITDB_DATABASE=rootdb
      - MONGO_USERNAME=arex
      - MONGO_PASSWORD=iLoveArex
  redis:
    image: redis:6.2.6
    container_name: arex-redis
    restart: always
    command: --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./arex-data/redis:/data
      - ./arex-logs/redis:/var/log/redis
